### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by oof100200** [ErzeKawek/EdenRing-1.20PR#5]
Minecraft 1.20.1
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'edenring'!
       at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
       at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
       at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
       at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63)
       at net.minecraft.server.Main.main(Main.java:112)
       at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
       at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
       at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
       at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
Caused by: java.lang.NoSuchFieldError: CLIENT_CONFIG
       at paulevs.edenring.config.Configs.<clinit>(Configs.java:20)
       at paulevs.edenring.registries.EdenItems.<clinit>(EdenItems.java:13)
       at paulevs.edenring.registries.EdenBlocks.<clinit>(EdenBlocks.java:48)
       at paulevs.edenring.EdenRing.onInitialize(EdenRing.java:49)
       at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
       ... 6 more

**Comment by Poopooracoocoo** [comment]
The crash occurs with both Eden Ring Reforked 0.6.7-1.20.4 and Eden Ring Reforked - 0.6.5-1.20.1.

Eden Ring Reforked runs perfectly fine on servers with Fabric Loader 0.14.25. But it fails to run on servers with Fabric Loader 0.15.0 and above.

[Fabric Loader 0.15.0](https://github.com/FabricMC/fabric-loader/releases/tag/0.15.0) fixed environment annotation stripping for fields. It must have to do with the `@Environment(EnvType.CLIENT)` annotations [here](https://github.com/search?q=repo%3AErzeKawek%2FEdenRing-Reforked+%22%40Environment%28EnvType.CLIENT%29%22&type=code). 

I think the fix is to remove any `@Environment(EnvType.CLIENT)` in common/server-side mixins, restoring the behaviour where Fabric Loader ignored it. I think the right way to do environment-only mixins is to have two completely separate mixins: one for common, one for client. 

See https://github.com/MoriyaShiine/extra-origins/commit/e6d4cd4ab32adc7114e420926e3b358ad65acaf7 for example

If you edit this yourself, you only need to modify the server jar, not the client.

**Comment by ErzeKawek** [comment]
> The crash occurs with both Eden Ring Reforked 0.6.7-1.20.4 and Eden Ring Reforked - 0.6.5-1.20.1.
> 
> Eden Ring Reforked runs perfectly fine on servers with Fabric Loader 0.14.25. But it fails to run on servers with Fabric Loader 0.15.0 and above.
> 
> [Fabric Loader 0.15.0](https://github.com/FabricMC/fabric-loader/releases/tag/0.15.0) fixed environment annotation stripping for fields. It must have to do with the `@Environment(EnvType.CLIENT)` annotations [here](https://github.com/search?q=repo%3AErzeKawek%2FEdenRing-Reforked+%22%40Environment%28EnvType.CLIENT%29%22&type=code).
> 
> I think the fix is to remove any `@Environment(EnvType.CLIENT)` in common/server-side mixins, restoring the behaviour where Fabric Loader ignored it. I think the right way to do environment-only mixins is to have two completely separate mixins: one for common, one for client.
> 
> See [MoriyaShiine/extra-origins@e6d4cd4](https://github.com/MoriyaShiine/extra-origins/commit/e6d4cd4ab32adc7114e420926e3b358ad65acaf7) for example
> 
> If you edit this yourself, you only need to modify the server jar, not the client.

Ok so, these issues thats mentioned will be fixed in 0.6.8 or 0.6.9

**Comment by ErzeKawek** [comment]
if this issue presists feel free to reopen this issue
